client/foundries.go

Currently, only the token owner's devices are shown by "device list".
Instead, let's show all devices attached to the owner's org(s) by
specifying ?shared=1 on the API call.
Signed-off-by: Michael Scott <mike@foundries.io>

device-list: show shared devices by default

---

client/foundries.go
cmd/device_list.go
cmd/device_show.go
cmd/device_show_update.go

The v51 version of aktualizr-lite include the ability to stream update events to the server:
https://github.com/foundriesio/aktualizr/commit/e231d3b3d6d4377c6c3777683f0b70bfbcde649c
The ota-lite server now saves tthose events and exposes them through the REST API. This change updates fioctl to display this information.

Add Support for new "device update" events

---

client/foundries.go
cmd/device_list.go
cmd/device_list_updates.go
cmd/targets_list.go
cmd/targets_show.go
go.mod
go.sum

This is a fairly big change to the way we display things. The intent is to make listing things easier to read. One side effect is that the listing doesn't always include as much information as it used to. However, the "show" versions of the commands should provide that detail when you need to drill down.
Here's an overview of the changes:
~~~
ID                                        TIME                  VERSION  TARGET
--                                        ----                  -------  ------
287-bbcb9b51-4b6b-42c4-9f65-b83b4c86bc09  2019-12-09T05:25:01Z  287      raspberrypi3-64-lmp-287
287-8c36f187-4eb5-440e-afa5-036b89f0997c  2019-12-09T05:21:54Z  287      raspberrypi3-64-lmp-287
....
~~~
~~~
NAME            FACTORY    TARGET                   STATUS   APPS
---- …

Improve CLI output

---

client/foundries.go
cmd/targets_edit.go

This command allows a user to make direct changes to the targets.json
file for a Factory. It tries its best to ensure no garbage is allowed
to be uploaded. However, this command should still be used with
caution.

Create a "targets edit" command

---

client/foundries.go
cmd/targets_prune.go

This helps reduce the size of target.json by also removing .dockerapp
files in the reposerver that are no longer referenced as a result of
removing a target(s).

Have targets-prune remove unused docker apps

---

client/oauth.go
subcommands/common.go

Most customers only belong to a single factory(org). This change detects
that and provides them the default they'll want in their fioctl config
so that they won't have to use the "-f" flag in commands requiring a
factory name.

login: Set default factory if there is one

---

client/foundries.go

The original OTA Lite API was return UTC timestamps but did not indicate
that. In order to prevent breaking older versions of fioctl, the API
was updated to return the non tz-aware timestamps to callers with the
"fioctl" user agent. By changing this value, fioctl will get the new
TZ aware timestamp.

client: Use the UTC aware device listing

---

client/foundries.go
subcommands/targets/image.go

Add sub-command to `targets` command to invoke ota-lite API handler
that invokes a JobServe CI job for assembling of a system image of the specified Target.
Format: `fioctl targets image <Target>`
depends on https://git.foundries.io/development/cloudplatforms/infrastructure/ota-lite/merge_requests/39

Add sub-command to trigger a system image assembling

---

client/oauth.go

Signed-off-by: Matthew Croughan <matthew.croughan@foundries.io>
Currently we only set the default `factory:` in `~/.config/fioctl.yaml` if a member is in 0 orgs. If a member is in 0 orgs then there is no factory that they are a member of. This logic means that if a user is a member of 1 factory/org, they will not have a default set which is incorrect.

client: set default org if orgs == 1, rather than == 0 - Fixes #52

---

subcommands/login/cmd.go

We already have logic to save the credentials if they are valid. There's
no point saving them initially - especially since they can be invalid
and cause the user to need to manually edit fioctl.yaml

bug #50 - don't save creds for bad login

---

cmd/docs.go
cmd/root.go
go.sum
subcommands/config/set.go
subcommands/devices/config_set.go

We can use this new `fioctl gen-rst` in conjunction with our docs to automagically produce CLI reference docs for this tool.

Add hidden command to generate RST docs

---

subcommands/devices/config_updates.go

Convert a list of strings into a single string that contains a comma-separated list of apps.

Fix docker_apps value in the config

---

subcommands/devices/show.go

In many cases, the information gathered by hwinfo can be quite
long.  This makes it hard to see the basic information.
Let's make the following changes to "device show":
- Hide the Hardware Information section by default with a hint
on how to show it if needed.
- Add a --hwinfo parameter to display the Hardware Information
section.
Signed-off-by: Michael Scott <mike@foundries.io>

Filter HW info with devices show parameter

---

subcommands/devices/list.go

A common feature request: More/different columns to be shown in device
listing. This keeps the default the same, but allows a user to show
any columns they'd like including Tags and DeviceGroup.

Add column customization to device listing

---

client/foundries.go
subcommands/common.go
subcommands/common_config.go
subcommands/config/cmd.go
subcommands/config/delete.go
subcommands/config/log.go
subcommands/config/set.go
subcommands/config/updates.go
subcommands/config/wireguard.go
subcommands/devices/config_log.go
subcommands/devices/config_set.go
subcommands/devices/show.go

There is still work to do with a non-trivial updates subcommand, but it's already possible to review config log/set/delete subcommands, all of which now behave consistently for factory/group/device config.

Generalize factory and device config commands, add ability to manage device group config

---

subcommands/config/device_group.go

fix a device-group help message referring to device instead of device group

---

client/foundries.go
subcommands/keys/rotate_root.go
subcommands/keys/rotate_targets.go

This allows a user to have their own private key capable of signing
targets.json

keys: Add a rotate-targets command

---

client/foundries.go
subcommands/keys/rotate_root.go
subcommands/keys/rotate_targets.go

A production root is the *exact* same as the root.json used in CI except
is has a targets signing threshold of 2.

keys: Add logic for syncing production root

---

client/foundries.go
subcommands/devices/config_wireguard.go
subcommands/devices/list.go

As we grow in the number of devices inside factories, our logic to
show everything in one pass breaks down. The backend now gives us 200
devices at a time. In the case there are more, the "-p <page>" argument
can be added to work through the device. Or, better yet, use filtering
logic.

Change pagination logic of device-list

---

subcommands/config/updates.go

- Drop the erroneous <device> parameter which is silently ignored
- Clarify the short text by making device plural
- Clarify the long text by making device plural and dropping the
<device> param in the examples.
- Clarify status message after change with "factory wide" or
"group wide"
Signed-off-by: Michael Scott <mike@foundries.io>

subcommands: config updates: fix help texts

---

client/foundries.go
subcommands/status/cmd.go

This adds a device group details info a factory status, similar to how we do this for wave status.
Example output (for one tag):
```
TARGET   DEVICES  INSTALLING  DETAILS
-------  -------  ----------  -------
683      1        0           `fioctl targets show 683`
617      1        0           `fioctl targets show 617`
0     *  2        1           
DEVICE GROUP  DEVICES  ON LATEST  ONLINE  INSTALLING
------------  -------  ---------  ------  ----------
new           1        1          0       0
test          2        0          0       1
```

Include device-group information into a factory status

---

subcommands/keys/rotate_root.go

2048 bit keys are not recommended

keys: Use 4096bit RSA keys

---

client/foundries.go
subcommands/devices/config_wireguard.go

The original method we used can't work on large numbers of devices. This
change uses a new API from the server to more efficiently find a free IP
address.

Use new wireguard-ips API for finding IP

---

client/foundries.go
subcommands/targets/list.go
subcommands/targets/prune.go
subcommands/targets/show.go

We used to produce "homogeneous targets" where each target-version would run the same containers and be based on the same source code. However, we now allow LMP builds to produce multiple targets that are based on different container branches and vice-versa. This means we need to be more verbose when displaying a target.
The change does 2 things:
1. you can show by target-version *and* target-name now. So `fioctl targets show raspberrypi4-64-lmp-38-production` is now valid and helpful for showing *exactly* what you need with these heterogeneous targets.
2. target-show shows each target. For example:
~~~
$ fioctl targets show 38                               
CI:	https://app.foundries.io/factories/andy-corp/targets/38/
Tags:        production
OSTree Hash: …

Fix some issues when displaying target information

---

subcommands/targets/prune.go

Target names used to look like intel-corei7-64-lmp-38  but now they
can look like intel-corei7-64-lmp-38-master and
intel-corei7-64-lmp-38-production if a factory does advanced tagging.
This uses a more fool-proof approach for finding the version

Fix bug in targets prune

---

subcommands/keys/resign_root.go
subcommands/keys/rotate_root.go

This function is needed to refresh an expiring root.json

Add the ability to resign the TUF root.json

---

client/foundries.go
subcommands/devices/cmd.go
subcommands/devices/list.go

This also fixes a previously malfunctioning just-mine argument in case if the user specified the factory

Require a factory argument for device list

---

client/foundries.go
subcommands/targets/list.go
subcommands/targets/show.go

The webui includes an "Origin Target" which can be quite handy when trying to debug factory targets. This adds the same type functionality. It also lets users customize what columns to show when listing targets.

targets: Show origin target where applicable

---

subcommands/secrets/update.go

This is the same approach that we added for fioctl-config-set

Allow secrets to come from a file

---

client/foundries.go

This API returns a pretty useful error response. Instead of running
`fioctl waves init -v` and parsing debug messages, you can get something
like:
$ fioctl waves init move-to-139-codeserver 139 production --keys /var/code/andy-corp/keys/offline-creds.tgz --source-tag production
ERROR: Failed to create a wave Targets validation failed
* CI Target differs for target raspberrypi4-64-lmp-139-master: not present in a wave
* CI Target differs for target intel-corei7-64-lmp-139-master: not present in a wave
* intel-corei7-64-lmp-38-production and intel-corei7-64-lmp-38-master conflict with each other's hardwareIds: intel-corei7-64
* intel-corei7-64-lmp-78-1 and intel-corei7-64-lmp-78 conflict with each other's hardwareIds: intel-corei7-64
* intel-corei7-64-lmp-79-1 and intel-corei7-64-lmp-79 …

client: Make better error message for waves-init

---

subcommands/devices/list.go

I have a bunch of synthetic devices which have never contacted our APIs.
And still all of them show as OK in the device list despite their last-seen is not set.

Show devices as offline when last-seen is not set

---

client/foundries.go
subcommands/keys/rotate_root.go

We now have customer's first root key available to download (to factory
admins). This allows us to make the first root rotation a little easier.

Introduce new initial key rotation logic

---

client/foundries.go

Use RFC3339 buildin time format instead of custom to parse device times

---

subcommands/devices/config_wireguard.go

The correct options are `enable` or `disable` but in the error message
it said `enabled` and `disabled`. That causes some confusion when giving
`enabled` as an argument which is wrong but then get the message it
would be a correct possible one.

wireguard: Fixed typo in error message displayed

---

subcommands/keys/rotate_root.go

During initial key rotation make sure the file does not exist already as
it could happen that when you do the initial rotation for two different
factories you might accidentially overwrite a file.

keys: Check if file exists during initial rotation

---

cmd/root.go
subcommands/docker/cmd.go

This allows you to do:
sudo fioctl configure-docker
It will create a symlink from fioctl->/usr/bin/docker-credential-fio
and update your docker config with the helper. After that, docker
commands "just work".

Add configure-docker helper

---

subcommands/login/cmd.go

* Due to a new layout of the settings pages,
application credentials now have their own
dedicated page.
Signed-off-by: Milo Casagrande <milo@foundries.io>

fix: update credentials dashboard url

---

subcommands/docker/cmd.go

Removed duplicate word "access" for `configure-docker --help`
Built and tested binary to validate change.
Signed-off-by: Katrina Prosise <katrina.prosise@foundries.io>

Fix mistype in help for configure-docker cmd

---

subcommands/common_config.go

Customer reported issue. They found this to be confusing/concerning:
$ fioctl devices config updates --tags tutorial ashitaka
ERROR: No changes found. Device is already configured with the specified options.
(exit code 1)
The suggestion was to exit with:
OK: No changes found. Device is already configured with the specified options.
I wasn't sure the "OK:" fit in with the rest of our commands, so I've
elected to just print the message and exit(0).

Don't exit with error when config unchanged

---

client/foundries.go
subcommands/keys/rotate_root.go

This change includes details for who/when/why root keys were rotated.
The backend API will verify this before committing the change.
Specifically:
* polis-id *must* be ID of the user making the change
* timestamp *must* be within 5 minutes of our clocks

keys: Include a changelog for root key rotation

---

client/foundries_factories.go
cmd/root.go
subcommands/factories/cmd.go

I run `fioctl get https://api.foundries.io/ota/factories/` about 12
times a week looking for the reposerver id value. It's nothing a normal
user needs, but it's easy enough to add in a way that makes customer
support a little easier.

Add a hidden "factories" subcommand

---

client/foundries.go
subcommands/targets/offline-update.go

Add a new command to download content required for an offline update.
1. TUF metadata.
2. Target's Apps.
3. Target's ostree repo.
Refreshing TUF metadata is out of scope atm.
Require extending of ota-lite to download production TUF metadata.

targets: Add command to fetch content for offline update

---

subcommands/targets/offline-update.go

Remove stopping of root meta fetching if 500 is received.
The issue in ota-lite was fixed so we should stop the fetch only if 404
is received. Any other response status codes are considered as errors.

targets: Stop root meta fetching if 404 received

---

subcommands/keys/ca_show.go

The `keys ca show --pretty` has a null pointer issue when users have
run `keys ca update` with a file that has a bunch of trailing
whitespace. This detects that situation and prevents the crash.

subcommands: Fix nil pointer issue in ca-show

---

client/foundries.go
subcommands/devices/apps_states.go
subcommands/devices/show.go

- Add printing of App states if present in the device json returned from
ota-lite.
- By default, just a state summary is printed for each App. If a new
flag `--appinfo` is specified then detail information about each App
is output.

devices: Show App states if present

---

subcommands/devices/apps_states.go

This makes the logs for an unhealthy app appear indented with the app
like:
```
nginx:
URI:	nginx
Hash:
Health:	unhealthy
State:	running
Status:	Up About a minute (unhealthy)
Logs:
| :2022/08/11 18:47:42 [notice] 1#1: start worker process 38
| :2022/08/11 18:47:42 [notice] 1#1: start worker process 39
| :2022/08/11 18:47:42 [notice] 1#1: start worker process 40
| :2022/08/11 18:47:42 [notice] 1#1: start worker process 41
| :2022/08/11 18:47:42 [notice] 1#1: start worker process 42
|
```

Indent app state logs

---

subcommands/post.go

There was an indexing error because we check for '@' first but if you give an empty body `-d ""` it will fail with an index[0] lookup error.

fix(post): Post subcommand index error

---

client/foundries.go
subcommands/keys/tuf_utils.go

We still use the garage-sign to sign targets; some of our customers also use it. So, we need to support the garage-sign required algorithm to generate the TUF key IDs. Which by the way differs a lot from the TUF specification.

Revert the TUF keyid field calculation to support garage-sign

---

subcommands/targets/show.go

The LmP is no longer a real factory, so we have to hack around a little to make this work.

Hack in ability to view LmP release SBOMs

---

client/foundries.go
client/foundries_tuf_root.go
subcommands/common.go
subcommands/devices/show.go
subcommands/docker/cmd.go
subcommands/keys/tuf_copy_targets.go
subcommands/keys/tuf_resign_root.go
subcommands/keys/tuf_rotate_offline_key.go
subcommands/keys/tuf_show_root.go
subcommands/keys/tuf_utils.go
subcommands/targets/edit.go
subcommands/targets/tag.go
subcommands/waves/init.go
subcommands/waves/show.go

* extract TUF root client routines into a separate file;
* rename TUF related routines to hold Tuf prefix or suffix where applicable;
* make private all TUF related functions (which are not re-used outside the `subcommands/keys` package;
* use canonical MarshalIndent to output user-friendly JSON data in all commands;
* some other minor non-functional code cleanups.

Refactoring to prepare for the TUF updates feature

---

subcommands/keys/tuf_crypto.go

It turns out that the Golang's native ed25519 package stores private keys in a custom way. In contrast, both Foundries.io and ota-community-edition store them in RFC 8032 compliant way.
The difference is that Golang concats the public key bytes to the end of private key bytes. Fortunately, ota-community-edition ignores that addendum i.e. keys generated by old fioctl work well. A problem is, however, that fioctl doesn't accept the initial Ed25519 key generated on the API.
This change fixes the problem by accepting both API-generated (RFC 8032 compliant) and old fioctl keys. It also goes further to store new Ed25519 keys in RFC 8032 format which is shorter (and well, standard).

Hotpatch: support the ota-lite generated Ed25519 keys

---

client/foundries.go
subcommands/targets/add.go

Add a new `targets` sub-command to add new Targets to the factory's TUF targets.
The sub-command allows adding new Targets taking either Apps or ostree hashes as an input, assuming that it will be called from the custom CI runs that build Apps and ostree-based rootfs correspondingly.
```
fioctl targets add --type app --tags <comma separate list of Target tags> --src-tag <source tag> <app URI> [<app URI>...]
```
```
fioctl targets add --type ostree --tags <comma separate list of Target tags> --src-tag <source tag> <hardware ID> <ostree commit hash> [<hardware ID> <ostree commit hash>...]
```

targets: Add command to create and post new targets

---

client/foundries.go
subcommands/targets/add.go

Add an optional parameter to specify details about the entity that produced Targets being added through `fioctl targets add` command.

targets: Add param to specify targets creator

---

subcommands/keys/tuf_rotate_all_keys.go

In case of expired root role the first action to take must be the TUF root key rotation. Otherwise, the API will complain about the too low expires field value.

Fixup: correct order for actions in tuf rotate-all-keys for expired root

---

cmd/root.go
subcommands/common.go
subcommands/common_unix.go
subcommands/common_windows.go
subcommands/docker/cmd.go
subcommands/keys/tuf_updates_rotate_offline_key.go

This PR just adds a way to safeguard against the potential situation that someone just installs docker but never runs it yet. In that case there is no `.docker` dir created and no `config.json`.
In addition the reason the error checking is changed is because of an [internal comment of golang itself](https://pkg.go.dev/os#IsNotExist).

fix(docker): Safeguard config.json not being found

---

.jobserv.yml
Makefile

I'm helping with LmP upgrade of Golang to 1.20 for fioconfig. So, my system-wide Golang version was upgraded to version 1.20. But, for some weird reason, older golangci-lint stopped working after that regardless of the go1.19 flag in go.mod.
It looks like it uses some of the Golang internals. The easiest solution is to upgrade golangci-lint to a newer version, which support Golang 1.17+.
Looking ahead, this is a good addition anyway to stay tuned.

Bump golangci-ling to 1.51.2

---

subcommands/devices/config_wireguard.go

wireguard: Don't allow a .0 device ip

---

client/foundries.go
subcommands/targets/deltas.go

Add an optional flag `--hw-id` to the static deltas generation command. The flag allows filtering `to` and `from` targets by a specified hardware ID.

deltas: Add optional hardware ID parameter

---

subcommands/keys/tuf_updates_sign_prod_targets.go

This somehow slipped through my attention during _many changes_.

Fixup: properly handle signing of all prod targets tags

---

subcommands/el2g/aws.go
subcommands/el2g/gateway.go
subcommands/keys/ca_create.go
x509/bash.go
x509/common.go
x509/golang.go

Key changes are related to implementing keys and certificates generation in Go instead of using external script. I've tried to mimic the exact same output when using the original openssl commands. The x509 library, however, always considers the `X509v3 Key Usage` fields as critical, and `X509v3 Extended Key Usage` as not critical, leading to the following differences on the generated certificates:
**`tls-crt`, openssl:**
```
X509v3 Extended Key Usage: critical
TLS Web Server Authentication
```
**`tls-crt`, Go:**
```
X509v3 Extended Key Usage: 
TLS Web Server Authentication
```
and
**`factory_ca.pem`, openssl:**
```
X509v3 Basic Constraints: 
CA:TRUE
X509v3 Key Usage: 
Certificate Sign
X509v3 Extended Key Usage: critical
TLS Web Client Authentication, TLS Web Server Authentication
``` …

Adjust subcommands to execute correctly on Windows

---

Makefile

We tested the PIE (position independent executable) and RELRO (read-only relocation) linker flags for quite some time in our server-side Golang executables; they behaved quite well. So, now it is time to apply them to the Fioctl as well to harden its run-time security.
Platform-wise this change has the following effects:
- On Windows and Arm Darwin: no effect, everything is a PIE on these platforms. The `make build` creates _exactly the same binary_.
- On Amd64 Darwin: make a PIE executable. The binary size is slightly increase, giving a slightly better run-time protection.
- On Linux: make a PIE executable using RELRO. (see https://github.com/golang/go/blob/master/src/cmd/link/internal/ld/lib.go#L1551). The binary size is increase by 10%, giving a way better run-time protection.
A size …

Security: set buildmode to PIE

---

subcommands/keys/tuf_updates_delete_offline_key.go
subcommands/keys/tuf_updates_rotate_offline_key.go
subcommands/keys/tuf_updates_sign_prod_targets.go

A newline was added before each list in command documentation across three commands. This should fix the issue where the output is used in sphinx and an indentation error causes a failure in the doc build.
Docs built without issue when changes were applied.
No related issue to link.

Fix indentation error for gen-rst

---

Makefile

This reverts commit 6105efe04beb399ef1cba597337385af343ca458.
It was breaking the Alpine Linux we use to generate docs. There is something more in play around PIE than expected.

Revert "Security: set buildmode to PIE"

---

.github/workflows/tuf.yml

This will run every hours. It will call a script:
https://github.com/foundriesio/fioctl/blob/tuf-metadata/refresh-metadata.sh
That will check if the timestamp is expiring in the next 48 hours. If so, it will update the timestamp for another 7 days.

github: Add cron job for refreshing TUF timestamp

---

.github/workflows/tuf.yml

This small filter will make sure it will only run on the foundriesio/fioctl repo by default.

fix(actions): don't run action on forked repos

---

client/foundries.go

The User API as defined by ota-lite wants a trailing slash. ota-lite sends a redirect back with the trailing slash. However, certainer certain reverse-proxies (GCP in our case) will try and resend the request but omit the auth header which results in our API getting an HTTP 401 response.

client: Fix user API URL

---

subcommands/git/cmd.go

Installing `git` on Windows will most likely place it in the `Program Files` directory.
Following our own [docs](https://docs.foundries.io/latest/getting-started/install-fioctl/index.html#configuring-git) on Windows will run the command as Administrator and place the resulting credential helper in `C:\Program Files\Git\bin\`. In order to make it work as seamless as possible on Windows we use the [absolute path configuration](https://git-scm.com/docs/gitcredentials#_custom_helpers) for the credential helper in the `.gitconfig` file managing the global configuration for git. 
On Windows the absolute path has to be converted into a different format.
1. All `\` have to become `/`
2. All spaces have to be 'escaped' making a ` ` into `\\ `
This works around symlinks, permission errors and other …

fix(git): Use absolute path instead

---

subcommands/keys/tuf_updates_rotate_offline_key.go

A search for the previous offline key to remove old signature fails for the initial rotation. This is expected as there is no offline key yet; so it should not prevent the key rotation.

Fix: the initial offline TUF targets key rotation

---

.github/workflows/lint.yml
.golangci.yml
.jobserv.yml
Makefile

This PR improves our linting process by:
- Update Makefile to improve lint target and add the lint-fix which can fix small issues like format and to sort the imports
- Add linter check using github action, removing the need to check logs. Example:
##Motivation
- Make it easier to fix lint issues and do the review
- Move checks to GitHub actions
- Ensuring consistent linting behaviour
- **Remove the need to set up lint manually. See that when we run make lint if the bin does not exist the target will download it**, see;
```
$ make check                         
make lint
/Users/camilamacedo/go/src/github.com/foundriesio/fioctl/bin/golangci-lint run
```
- Allow leverage in the common checks to avoid errors; see proposed follow-up:

(chore): Add linter improvements

---

.github/dependabot.yml

Introduce Dependabot to ensure consistent and effortless updating of the project's dependencies.
GitHub's Dependabot will perform weekly checks and automatically create pull requests to update the Dockerfile, GitHub Actions, and go.mod dependencies. With a reliable Continuous Integration (CI) in place to validate the tool's functionality, this approach significantly streamlines the review process. This allows us to effortlessly keep our project updated, minimizing technical debt and promptly addressing any potential Common Vulnerabilities and Exposures (CVEs).

(chore) : add dependabot to keep project updated

---

client/foundries.go
subcommands/waves/init.go

Adds a warning message to inform users about the recommendation to use Static Deltas to optimize OTA downloads.
The message only appears when users create weaves that do not have static deltas.
When no Static Deltas are in place:

(feat): Warning users about create OSTree static deltas before rolling out waves

---

.github/workflows/binaries.yml

This PR introduces new tests aimed at building binaries for all supported platforms. The construction of these binaries utilizes make commands, ensuring their functionality. For this process, we've employed GitHub Actions and QEMU.
- These additions appear sufficient in covering various scenarios like allowing us to get merged bumps without breaking changes without overthinking and manual tests.

chore: Add tests to ensure that build works and is functional

---

.github/workflows/test-pki.yml
Makefile
README.md
client/foundries_pki.go
go.mod
go.sum
subcommands/keys/ca_create.go
x509/bash.go
x509/common.go
x509/common_test.go
x509/golang.go
x509/hsm_test.go
x509/storage_filesystem.go
x509/storage_pkcs11_cgo.go
x509/storage_pkcs11_tool.go

An idea is to continue building Fioctl statically, and provide HSM support by wrapping pkcs11-tool.
The tool is available for Linux, Windows, and Darwin; a user can also build from source.
The PR contains 3 implementations:
- Our current/legacy Bash based PKI, which is now turned off. The HSM support for it was fixed, and script running made more secure.
- The Golang based implementation was enhanced with pkcs11-tool to support HSM devices, and turned on for all platforms.
- An alternative native Golang implementation via CGo package is also added, but turned off by default as it only works for a dynamically linked (not static) binary.
I find it reasonable to keep all 3 implementations for reference.

WIP: pkcs11-tool based HSM support

---

subcommands/targets/offline-update.go

This commit prevents the execution of "targets offlile-update" using a destination directory that already contains update data (i.e., "ostree_repo" or "apps" subdirectories). There is no check for the tuf subdirectory, since the metadata in that subdir is updated by default, and there is no conflict.
The content of the destination directory can be cleaned up automatically if the new --force option is used.

targets: offline-update: Check if dest dir already has data

---

cmd/root.go

We expected this function to be provided by Cobra, but it does not make that check. So, before the some commands accepting positional arguments allowed values like "" or ''. These are affectively empty strings, that is equivalent to no value in all or commands.
As a matter of fact, some commands were panicking on this, some failing on API level with 400, 401, 404, 405, or 500 errors. The exact error which happened seems quite random. In the worst case this could lead to bad behavior, although I found no such use case.
This disallows erroneous (empty) positional arguments once and for all commands. All (random) misbehaving commands I tried are now fixed.

Bugfix: deny empty positional arguments in all commands

---

client/foundries_pki.go
subcommands/keys/ca_create.go
subcommands/keys/ca_rotate_tls.go
subcommands/keys/est.go

Supported operations:
- Rotate EST certificate (only cleanup, tested happy-path, TBD end-2-end).
- Rotate TLS certificate (new feature, tested end-2-end).
Device CA rotations will be a separate PR, as they are more complex.

Feature: TLS certificate rotation for the factory PKI

---

subcommands/keys/ca_show.go

Currently, we show these extensions and unknown OIDs.
But, our Golang implementation always adds these extensions (as non-critical).
So, it is better to show them to look more professional.

Feature: show subject key ID and authority key ID extentions in CA

---

subcommands/keys/ca_add_device_ca.go
x509/bash.go
x509/golang.go

For the local device CA:
- A user can generate new device certificates using any added local CA, for which they possess a cert and private key.
For the online device CA:
- The device API will use the new online device CA to generate device certificates.
- Old online device CA key is over-written, so that it can no longer be used.
All newly added device CAs become trusted by the device gateway.
This command does not remove any existing device CAs from the list of trusted device CAs.

Feature: allow to add more online or local device CAs

---

Makefile

It simplifies code where relevant.
I've hit it several times already that one of linters complains about formatting of auto-formatted code. This option helps removing the routine of fixing such warnings.

Tooling: enable gofmt -s option

---

client/foundries_pki.go
subcommands/keys/ca_revoke_device_ca.go
subcommands/keys/ca_show.go
x509/bash.go
x509/common.go
x509/common_test.go
x509/golang.go
x509/storage_filesystem.go

Currently, an API allows to simply remove the device CA from a list of CAs.
This change implements the device CA removal via the X.509 certificate revocation.
That way, a user is required to crypto-sign the operation using the factory root CA.
Thus, we both obtain an cryptographic conscent from the user for this operation and protect against several scenarios:
- An accidental device CA removal by passing a wrong file to "keys ca update".
- An intentional device CA removal by bad admin who does not possess the factory root CA.
After this change, the API will be changed to require the "ca-crt" field to contain all device CAs which:
- Are already present in the "ca-crt" list on the backend.
- And are not explicitly listed in the "ca-revoke-crl" list.
There are two new operations introduced: …

Feature: allow to revoke or disable device CA

---

cmd/root.go

We upgraded cobra to 1.8.0 with https://github.com/foundriesio/fioctl/pull/329.
So we can use its fix for persistent hooks traversal https://github.com/spf13/cobra/pull/2044, instead of our workaround for it from https://github.com/foundriesio/fioctl/pull/312.

Cleanup: use the cobra fix for persistent hooks traversal

---

subcommands/login/cmd.go

Just a simple way of shifting the way the default URL gets set.
If the command line switch is given, then use that URL. 
Otherwise if a config URL is already set, use that URL.
Otherwise fallback to the default we were using previously.

feat(login): better defaults for custom URLs

---

subcommands/keys/tuf_utils.go

This is an important hot fix.
Currently, the API fails on subsequent key rotations due to denying old key owners.
Fortunately, customers should not see it, as the first rotation succeeds. But, when the user wants to rotate the key which was rotated using new Fioctl - that second rotation fails.

Hotfix: clean up key owners when rotating TUF keys

---

client/foundries.go
client/foundries_tuf_root.go
subcommands/common.go
subcommands/devices/list.go
subcommands/keys/tuf_resign_root.go
subcommands/keys/tuf_updates_add_offline_key.go
subcommands/keys/tuf_updates_delete_offline_key.go
subcommands/keys/tuf_updates_rotate_offline_key.go
subcommands/keys/tuf_updates_rotate_online_key.go
subcommands/keys/tuf_updates_set_threshold.go
subcommands/keys/tuf_updates_sign.go
subcommands/keys/tuf_updates_sign_prod_targets.go
subcommands/keys/tuf_utils.go
subcommands/waves/list.go

This is a set of improvements using the new APIs:
- Ability to show only active waves using `waves list --only-active`.
- Ability to auto-re-sign active waves targets when running `keys tuf updates rotate-offline-key -r targets`.
- Ability to manually re-sign selected waves using `keys tuf updates sign-prod-targets --waves=<wave-list>`.
- Detect when user tries to re-sign non-existing prod targets tag using `keys tuf updates sign-prod-targets --tags=<tag-list>`.
- Verify that all `page, limit` arguments are non-negative numbers in `devices list, devices list-denied, waves list`.

Feature: re-sign all active waves on TUF targets key rotation

---

subcommands/keys/ca_add_device_ca.go
subcommands/keys/ca_revoke_device_ca.go

This command expects a filename and not a path. This change makes the error more clear.
fixes issue #344

keys: Don't allow slash in device-ca

---

client/foundries.go
subcommands/targets/offline-update.go

- Add ability to download wave's TUF metadata and its target content to the offline update bundle.
- Correct checking whether the production target exists for a given tag

offline-update: Add wave target pull support

---

subcommands/common_config.go

Instead of overriding the input given with what our api is giving back, it is much better to just take what the user is giving us as what needs to be set.

fix(device): always take apps input as source of truth

---

client/foundries.go

The default Golang client will advertise to the HTTP server that it can handle gzip compressed response encoding. This is true, but it breaks our artifacts.go code for doing download progress.
This is because the default behavior of the transport is to:
* provide the proper reader to decompress the response
* update the content-length header to be -1
The -1 breaks our logic. This fix gets us back to how things used to work before CloudFlare started compressing the responses.

client: Disable compression in default transport

---

client/foundries.go
subcommands/targets/offline-update.go

Add a proper support of multi-target bundles with all required checking and security. It is achieved by adding an additional signed metadata file/json that contains an info about a bundle's targets.
- Send `bundle-targets.json` to the `target/meta` handler if exists.
- Receive and store the bundle targets meta if the handler returns them.
The `bundle-targets.json` will be used by the offline updater to determine targets that can be installed by using a given bundle.

offline-update: Add multi-target bundle support

---

subcommands/targets/offline-update.go

If a user has not taken either root or target keys offline, then there are only two root versions in a given factory.
In such a case, the bundle will have no root metadata.
Therefore, to make the 'show' command work properly, the command needs to fetch the latest (i.e., version 2) root metadata from the backend.

targets: Use online root meta if not found locally

---

client/foundries.go
subcommands/status/cmd.go
subcommands/waves/status.go

We are going to remove this field from our APIs.
It is causing us performance problems, while providing little value.

Deprecation: remove re-installing fields from factory/wave status

---

subcommands/targets/offline-update.go

Apps might be explicitly turned off or intersection of target apps and the app shortlist specified for offline update is empty (for specific tag). In this case there is no a download URI to fetch an app tarball for a given bundle. This change handles this case properly instead of yielding an error.

targets: Handle absence of apps for offline update

---

subcommands/docker/cmd.go
subcommands/git/cmd.go

When using it like `fioctl configure-git --creds-path ~/.config` there is no problem however if you use it like `fioctl configure-git --creds-path=~/.config` there is.
The reason lies in the fact that in the first example the shell already expands the ~ into the absolute path of the homedir, in the second it will not.

fix(git): expand user home dir first

---

client/foundries.go

The `fioctl targets add` command must retain the arch and image-file custom fields from the previous target. Otherwise, the publish-compose-apps operation for new targets will fail.
This commit adds both field to the structure used in the process, allowing the required fields to be copied to the target being added.
---
@mike-sul after some additional tests with targets creation, it is clear that this change is in fact required.

targets: Add missing fields to TufCustom

---

subcommands/targets/offline-update.go

Allowing the specification of a local ostree repo during offline bundle creation is required when a custom ostree repo is in use (`fiopush` + `fioctl targets add`).
This PR also add a warning message if the ostree repo does not contain the expected hash.

offline-updates: Allow specification of local ostree repo

---

client/foundries.go
subcommands/targets/add.go

For custom apps targets, origUri must be set, while uri and origUriApps must be empty.
For custom ostree targets, origUriApps must be set, while uri and origUri must be empty.
---
@mike-sul this change seems to work, but is not enough. Apps targets generated by our CI are keeping the `origUriApps` field set. I'd say we need to fix the behavior there before merging this change to fioctl. Otherwise, an old `origUriApps` value is carried on indefinitely.

targets: Handle OrigUri and OrigUriApps when adding targets

---

cmd/root.go
subcommands/git/cmd.go

This set of changes fixes some rough edges with our git credential helper.
The first change fixes something that "works" but was reckless where we accidentally configured our helper for all "https:*" URLs.
The last 2 changes address the complexity we've had trying to reliably make a symlink from "fioctl -> git-credential-fio". It turns out we never needed to do that and could have gone with a simpler approach that has less ways to fail.

Fixes to the git credential helper

---

.github/workflows/binaries.yml

This should fix our deprecated GitHub action workflow actions.

chore(actions): update to v4 for artifacts

---

subcommands/targets/tag.go

This will not allow the user to potentially shoot themselves in the foot by denying potential empty tags list.

fix(targets): make tag subcommand deny empty tags

---

cmd/root.go

The completion command fails now on `fish` because when you run `fioctl ` and then hit `<Tab>` then the auto complete will fail because we will always return an error, which leads to not seeing all the options possible.

fix(root): allow empty args for autocomplete

---

.github/workflows/release.yml

The move to Github Enterprise seems to require this.

release: Fix permission required for pushing releases

---

go.mod

This resolves a subtle bug with some toolchains being unable to resolve 1.24.

Fix golang version to 1.24.4

---

client/foundries_device.go
client/foundries_fiotest.go
subcommands/devices/tests.go
subcommands/targets/tests.go

This compliments the recent API change to support looking up test results by Device rather than Target.

Add `devices tests` subcommand

---

subcommands/devices/updates_show.go

We tried adding support for `-by-uuid` to all device subcommands:
https://github.com/foundriesio/fioctl/commit/89be418dfcded2565a7357c92453fb8840b85ab5
However, the logic in `addUuidFlagToChildren` only adds the flag to commands that have subcommands. The `updates` command does not have any which causes us to print a warning each time you run the command:
```
ERROR: flag accessed but not defined: by-uuid
```
This causes a small bit of duplication, but seems to be the easiest way to fix this issue.

devices updates: Fix `by-uuuid-flag` warning
