foundriesio/fioctl

client/foundries.go, cmd/device_list.go, cmd/targets_list.go
* allow listing just the devices you own (`--just-mine`)
* show network information reported from aktualizr
* filter device listing by filepath patterns
=> Device list improvements

client/foundries.go, cmd/device_list.go
=> device-list: Include configured tags

cmd/targets_list.go
=> targets-list: Fix sorting by version

client/foundries.go, cmd/device_list.go, cmd/users.go
The OTA Lite API now includes some user lookup information that's handy for this command.
=> Add support for new users API

.gitignore, client/foundries.go, cmd/secrets_update.go
allows nil/null to be set to the secret value to trigger deletion of a secret
=> allows for deletion nil/null values

client/foundries.go, cmd/device_list.go, cmd/device_show.go
added output for up-to-date attributes
=> added output for up-to-date attributes

client/foundries.go, subcommands/targets/show.go
=> targets: Include URLs that produced the build

go.mod, subcommands/devices/config_updates.go
=> Add "devices config updates" command

.jobserv.yml, Makefile
=> CI: Enable jobserv PR testing

subcommands/config/wireguard.go, subcommands/devices/config_wireguard.go
=> Add wireguard configuration commands

client/foundries.go, cmd/root.go, subcommands/devices/list.go, subcommands/status/cmd.go
=> Add a new factory status command

client/foundries.go, subcommands/targets/tests.go
=> tests: Add support for displaying test artifacts

subcommands/targets/image.go
=> Tail output of the image CI job

client/foundries.go, subcommands/targets/edit.go, subcommands/targets/image.go, subcommands/targets/prune.go, subcommands/targets/tag.go
=> Use web-url for CI URL

client/foundries.go, subcommands/targets/image.go
=> Param to list apps to preload into a wic image

subcommands/devices/config_updates.go
=> devices-config-updates: Hide a compose app dir param

.gitignore, client/foundries.go, subcommands/config/device_group.go, subcommands/devices/config_group.go, subcommands/devices/show.go
A follow up from https://github.com/foundriesio/fioctl/pull/66
A GitHub doesn't allow to continue a pull request after a force push into a branch.
=> add device group management and assignment commands

subcommands/config/set.go, subcommands/devices/config_set.go
=> Allow config-set commands to read from stdin

client/foundries.go, subcommands/devices/updates_show.go
depends on https://github.com/foundriesio/aktualizr-lite/pull/48
=> updates: Show event details if present

subcommands/devices/cmd.go, subcommands/devices/updates_list.go, subcommands/devices/updates_show.go
=> Improve usability of device updates

client/foundries.go, subcommands/keys/cmd.go, subcommands/keys/rotate.go
This does two things:
* clean up some over-designed/dead code
* get key rotation working again
=> Clean up TUF key rotation

subcommands/targets/artifacts.go
=> target artifacts: Give better error for invalid target

subcommands/targets/prune.go
=> targets: Add --keep-last for pruning

client/foundries.go, cmd/root.go, subcommands/targets/edit.go, subcommands/targets/list.go, subcommands/targets/prune.go, subcommands/targets/show.go, subcommands/targets/tag.go, subcommands/waves/cancel.go, subcommands/waves/cmd.go, subcommands/waves/complete.go, subcommands/waves/init.go, subcommands/waves/list.go, subcommands/waves/rollout.go, subcommands/waves/show.go
The first draft so that I don't lose it
=> Add commands to create, rollout, complete, cancel, list and view waves

client/foundries.go, subcommands/waves/status.go
=> Add a wave status command

subcommands/waves/cmd.go
This makes it consistent with the other commands
=> subcommands: Make wave->waves

client/foundries.go, subcommands/targets/deltas.go
=> Add new static-delta command

client/foundries.go, subcommands/common_config.go, subcommands/config/updates.go, subcommands/devices/config_updates.go, subcommands/devices/list.go, subcommands/devices/show.go
A device can only follow a single tag. This fixes all the code referencing that.
=> Change references of device tags to tag

subcommands/common_config.go, subcommands/config/set.go, subcommands/devices/config_set.go
=> Support a file path in `fioctl [device] config set` commands.

go.mod, go.sum, subcommands/common.go, subcommands/status/cmd.go, subcommands/targets/show.go, subcommands/waves/status.go
=> Use indented tabby instead of home-grown intent writer

client/foundries.go, subcommands/devices/list.go
=> Add device-group ability to devices-list

client/foundries.go, subcommands/devices/show.go
=> Add logic to display secondary ecus if present

subcommands/targets/list.go, subcommands/targets/show.go, subcommands/waves/init.go
* require a tag name when creating a wave
* fix issue with "target collisions"
* add ability to display production targets.json
* add ability to show a production target
=> Usability improvements for waves

subcommands/login/cmd.go
People frequently find themselves updating the scopes of a fioctl token
and not having an easy way to have the changes updated locally. This
change introduces a simple hack to force a token refresh that will
include the updated scopes
=> Add a "login --refresh-access-token" option

Makefile, client/foundries.go, subcommands/targets/tag.go
This changeset adds some usability improvements to how targets are tagged.
=> Improvements to target tagging

client/foundries.go, subcommands/devices/chown.go, subcommands/devices/config_delete.go, subcommands/devices/config_group.go, subcommands/devices/config_log.go, subcommands/devices/config_set.go, subcommands/devices/config_updates.go, subcommands/devices/config_wireguard.go, subcommands/devices/delete.go, subcommands/devices/rename.go, subcommands/devices/show.go, subcommands/devices/updates_list.go, subcommands/devices/updates_show.go
=> Pass the required factory argument to an API for all device commands

client/foundries.go, subcommands/targets/image.go
=> Add ability to override ci-scripts for target-image

client/foundries.go, subcommands/targets/artifacts.go
* make more visible highlights to status changes
* fix tailing crash when client hits HTTP error
* add ability to tail ci jobs
=> Console tailing improvements

client/foundries.go, cmd/root.go, subcommands/teams/cmd.go, subcommands/users/cmd.go
Extended the users command and added new teams command.
=> users: Added user details and teams

README.md
Signed-off-by: Cervenka Dusan <cervenka@acrios.com>
=> Fixing markdown issues

subcommands/common.go
When running a command that requires a factory such as `fioctl targets
list`, you'd see:
ERROR: Required flag "factory" not set
This change checks for the login first (which might set the factory) to
give the user a more accurate reponse.
=> common: Fix check for factory

subcommands/config/updates.go
We are going to start requiring device-groups when setting aklite update
settings. Doing fleet wide is too risky.
=> config-updates: Require a device-group

subcommands/keys/resign_root.go
This was missed when we added this new functionality to rotate-root
=> Add change reason to resign-root command

subcommands/keys/rotate_targets.go
Update the root role's reason field if a new version is generated
because a target role key was rotated.
=> keys: Update "reason" if target key is rotated

subcommands/targets/offline-update.go
=> targets: offline-update: Make Apps optional

subcommands/common.go, subcommands/keys/ca_show.go
Cobra does not yet have mutually exclusive arguments, so I bolted this
into our common code.
=> keys: Add ability to show subset of certs

.jobserv.yml, Dockerfile.build, client/foundries.go, client/oauth.go, subcommands/common.go, subcommands/common_config.go, subcommands/docker/cmd.go, subcommands/events/create.go, subcommands/events/listen.go, subcommands/keys/ca_create.go, subcommands/keys/ca_update.go, subcommands/secrets/update.go, subcommands/targets/edit.go, subcommands/waves/init.go
=> Upgrade Golang to 1.19 for release building 

subcommands/el2g/aws.go, subcommands/el2g/gateway.go
=> Remaining linter warnings for io/ioutil from a parallel merge

client/foundries_el2g.go, subcommands/el2g/devices.go, subcommands/el2g/status.go
@vkhoroz - this actually one commit - https://github.com/foundriesio/fioctl/commit/bdcb2acfab4046762a9c15fea95a12a3dea5a314 its just dependent on PR #179
=> el2g: Add status command

client/foundries.go, cmd/root.go, subcommands/post.go
Much like `fioctl get`, this command can be handy for people trying to interact/experiment directly with our API.
=> Add a new hidden "post" command

subcommands/targets/offline-update.go
=> targets: Add a flag to skip Apps download for offline update

client/foundries.go
Most of our APIs return the well-formatted JSON error for 4xx status codes. Print these errors in a user-friendly output.
=> Improve: return well formatted errors where API allows

subcommands/keys/tuf_updates_apply.go, subcommands/keys/tuf_updates_init.go, subcommands/keys/tuf_updates_rotate_offline_key.go, subcommands/keys/tuf_updates_sign.go
=> Do not require the txid for the user who initiated TUF updates

client/foundries_tuf_root.go, subcommands/common.go, subcommands/keys/tuf_resign_root.go, subcommands/keys/tuf_rotate_offline_key.go, subcommands/keys/tuf_updates.go, subcommands/keys/tuf_updates_apply.go, subcommands/keys/tuf_updates_init.go, subcommands/keys/tuf_updates_rotate_offline_key.go
=> Feature: move TUF key rotation commands to use TUF updates API

subcommands/waves/init.go
This should support pruning old targets as part of starting a new wave.
=> feat(wave): prune multiple targets

client/foundries.go
=> image-assemble: Correctly append app shortlist query param

client/foundries_tuf_root.go, subcommands/keys/tuf_crypto.go, subcommands/keys/tuf_rotate_all_keys.go, subcommands/keys/tuf_updates_apply.go, subcommands/keys/tuf_updates_rotate_offline_key.go, subcommands/keys/tuf_updates_rotate_online_key.go, subcommands/keys/tuf_utils.go
=> Feature: command to rotate online TUF keys

subcommands/targets/prune.go
=> Improve the targets prune help by adding examples

client/foundries_tuf_root.go, go.mod, go.sum, subcommands/keys/tuf_updates_review.go
=> Feature: ability to show tuf updates in human readable and diff formats

client/foundries_tuf_root.go, subcommands/keys/tuf_updates_review.go, subcommands/keys/tuf_utils.go
In the new API we return some advices how to improve the customer's TUF metadata. This change will show these advices to the user.
=> Feature: show advices for TUF updates

subcommands/git/cmd.go, subcommands/git/cmd_unix.go, subcommands/git/cmd_windows.go
This addresses some issues found on Windows and MacOS
=> Fixes the git credential helper install logic

subcommands/common.go, subcommands/common_unix.go, subcommands/common_windows.go, subcommands/docker/cmd.go, subcommands/git/cmd.go
Just added the same improvements as the git helper to make the DX better across all platforms.
=> fix(docker): Same improvements as git helper

client/foundries.go, subcommands/common.go, subcommands/devices/list.go, subcommands/waves/list.go
=> feat(waves): Implement pagination

client/foundries.go, subcommands/devices/list.go
=> Feature: filter device list by target name pattern

client/foundries.go, subcommands/devices/list.go
=> Feature: allow sorting by last-seen and/or name asc/desc

client/foundries.go, subcommands/users/cmd.go
Print scopes and device groups of each user team.
=> users: Print details about user teams

client/foundries.go, subcommands/waves/rollout.go
=> Feature: ability to rollout a wave to a subset of matching devices

client/foundries.go, subcommands/waves/rollout.go
This adds 3 options: --dry-run, --print-names, --print-uuids. Below is an example output with all 3 options enabled:
```
$ fioctl-linux-amd64 waves rollout test-wave --limit=2 --dry-run --print-uuids --print-names
A wave would be rolled out to 2 devices in your factory.
Below is a full list of these devices:
a4419ffb-b8ce-492c-8e50-4bce9a2398a1 (prod-dev1), 7a733e81-f948-43a9-a358-56f3deb5f184 (prod-dev2)
```
=> Feature: add verbosity and dry-run flags to wave rollout

client/foundries.go, subcommands/waves/show.go, subcommands/waves/status.go
=> Wave status updates to account for a partial rollout to groups

subcommands/common.go, subcommands/keys/tuf_updates_rotate_offline_key.go, subcommands/keys/tuf_utils.go, subcommands/waves/init.go
=> Support multi-key TUF root in key rotation and signing commands

client/foundries.go, client/oauth.go, subcommands/common.go, subcommands/events/listen.go, subcommands/login/cmd.go, subcommands/targets/tail.go
These are the changes that were required to allow fioctl to fully integrate with a MEDs instance.
=> Meds updates

subcommands/keys/tuf_utils.go
=> Fixups to allow multiple TUF root signatures

subcommands/keys/tuf_updates_add_offline_key.go, subcommands/keys/tuf_utils.go
=> Feature: ability to add more than one offline TUF signing key

subcommands/keys/tuf_updates_delete_offline_key.go
=> Feature: ability to delete offline TUF signing key

subcommands/keys/tuf_updates_rotate_offline_key.go, subcommands/keys/tuf_updates_sign_prod_targets.go, subcommands/keys/tuf_utils.go
=> Feature: ability sign production targets during TUF root updates

client/foundries.go, subcommands/common_config.go, subcommands/devices/show.go
Just added the information on who created the config.
=> feat(config): Show CreatedBy user name

subcommands/keys/tuf_updates_rotate_offline_key.go
Mike Sul found a regression in the recent changes related to multi-key support. When there is no offline targets key yet - the `rotate-offline-keys --role=targets` fails.
A reason is that in a new code we always require an old key to exist inside the tgz file. But that condition cannot be met when there are no offline targets keys yet.
A workaround is to use a new command `add-offline-key --role=targets`. But, we need an existing command to behave the same way in this case for backward-compatibility.
=> Fixup: fix the first offline targets key rotation

client/foundries.go, subcommands/waves/sign.go
=> Feature: ability to sign a wave by more than 1 key

client/foundries_tuf_root.go, subcommands/keys/tuf_updates_add_offline_key.go, subcommands/keys/tuf_updates_rotate_offline_key.go, subcommands/keys/tuf_utils.go
=> Feature: track TUF key ownership

subcommands/waves/init.go
Signed-off-by: Camila Macedo <camila.macedo@foundries.io>
=> chore: improve static delta message for waves init command

.github/workflows/binaries.yml
=> Test: verify that Sphinx docs build well

.gitignore
=> .gitignore: tuf-metadata tooling cleanup

client/foundries.go, client/foundries_teams.go, client/foundries_users.go, subcommands/common_config.go, subcommands/config/log.go, subcommands/devices/config_log.go
=> fixup! feat(config): Show CreatedBy user name (#246)

subcommands/git/cmd.go
@camilamacedo86 This one will fix the git credential helper to also allow other domains for where the source is located.
=> fix(git): make source url dynamic for git helper

.github/workflows/release.yml
It turns out this one was out of sync with other workflows, so I missed it.
=> Upgrade Golang in release job.

subcommands/targets/show.go
Extend the `show` command with a flag to print target custom data in raw JSON format.
It is often useful to view all fields of a target's custom data in its original JSON form, especially when debugging or troubleshooting issues related to updating a device to a specific target.
=> show: Add flag to print target custom json
